name: Automations on PR open
on: 
  pull_request:
    types: [closed]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Delete S3 Branch
        run: aws s3 rm "s3://roamjs.com/${{ github.event.pull_request.number }}" --recursive
