name: Push Site to Branch
on: pull_request

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  APP_BASE_PATH: /${{github.event.number}}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:next
      - name: Upload
        run: |
          aws s3 sync out s3://roamjs.com$APP_BASE_PATH
          for filename in out/*.html; do
              HTML=$(basename "$filename" .html)
              aws s3 cp $filename s3://roamjs.com$APP_BASE_PATH/$HTML --content-type "text/html"
          done
      - name: Invalidate Cache
        run: |
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='roamjs.com'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
