name: Automations on PR open
on: 
  pull_request:
    types: [opened]

env:
  GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        run: npm install
      - name: Automate
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: npm run automate
